# Generated by Django 5.2.1 on 2025-05-19 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_of_payment', models.CharField(choices=[('Mail Done', 'Mail Done'), ('Online Transfer', 'Online Transfer'), ('Cheque', 'Cheque'), ('Cash', 'Cash'), ('DD', 'Demand Draft')], max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial Payment'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], max_length=50)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('next_follow_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField()),
                ('due_days', models.IntegerField()),
                ('present_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Follow-up',
                'verbose_name_plural': 'Payment Follow-ups',
            },
        ),
        migrations.CreateModel(
            name='HospitalLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('hospital_type', models.CharField(choices=[('Direct Hospital', 'Direct Hospital'), ('Distributed', 'Distributed'), ('Other', 'Other')], max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('telecalling_response', models.JSONField(default=list)),
                ('decision_maker', models.JSONField(default=list)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('followup_time', models.TimeField(blank=True, null=True)),
                ('communication_channel', models.CharField(blank=True, choices=[('SMS', 'SMS'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('Phone', 'Phone')], max_length=20, null=True)),
                ('promotional_messages', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('ltr', 'Liter'), ('pcs', 'Pieces'), ('box', 'Box'), ('nos', 'Numbers')], default='pcs', max_length=10)),
                ('hsn_sac', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.category')),
            ],
        ),
    ]
