# Generated by Django 5.2.1 on 2025-08-06 10:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_expensecategory_lead_customer_customer_id_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-started_date'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this project currently active?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(help_text='Enter a unique identifier for this project (e.g., PRJ-001, WEBSITE-2025)', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(help_text='Enter a descriptive name for your project', max_length=200, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='started_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Select the project start date'),
        ),
        migrations.CreateModel(
            name='HospitalLeadParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_parts', to='leads.hospitallead')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.parts')),
            ],
            options={
                'verbose_name': 'Hospital Lead Part',
                'verbose_name_plural': 'Hospital Lead Parts',
                'unique_together': {('hospital_lead', 'part')},
            },
        ),
        migrations.CreateModel(
            name='HospitalLeadProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_products', to='leads.hospitallead')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.product')),
            ],
            options={
                'verbose_name': 'Hospital Lead Product',
                'verbose_name_plural': 'Hospital Lead Products',
                'unique_together': {('hospital_lead', 'product')},
            },
        ),
    ]
