# Generated by Django 5.2.1 on 2025-06-10 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_parts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parts',
            options={'ordering': ['-created_at'], 'verbose_name': 'Parts', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AddField(
            model_name='parts',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.category'),
        ),
        migrations.AddField(
            model_name='parts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.product'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parts',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
