# Generated by Django 5.2.1 on 2025-06-20 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product_unit', models.CharField(blank=True, choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('ltr', 'Liter'), ('box', 'Box'), ('nos', 'Numbers'), ('mtr', 'Meter'), ('sqft', 'Square Feet'), ('set', 'Set')], max_length=10)),
                ('hsn_sac', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='customer_products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='leads.customer')),
            ],
        ),
    ]
