# Generated by Django 5.2.1 on 2025-06-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_customerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
