# Generated by Django 5.2.1 on 2025-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_remove_customerproduct_installation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='warranty_period_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
