# Generated by Django 5.2.1 on 2025-07-23 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_customerproduct_installation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorproduct',
            old_name='category_id',
            new_name='serial_number',
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.category'),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='warranty_period_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorproduct',
            name='product_unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('meter', 'Meters'), ('liter', 'Liters'), ('box', 'Box'), ('set', 'Set'), ('roll', 'Roll'), ('packet', 'Packet')], default='pcs', max_length=50),
        ),
    ]
